name:                turnstile
version:             0.1.0.0
github:              "MatthewZito/turnstile"
license:             BSD3
author:              "Matthew Zito (goldmund)"
maintainer:          "exbotanical@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A distributed CI server environment
category:            Web, CI/CD

description:         Please see the README on GitHub at <https://github.com/MatthewZito/turnstile#readme>

default-extensions:
- BlockArguments
- DeriveAnyClass
- DeriveGeneric
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- StrictData

dependencies:
- aeson
- async
- base
- butcher
- hslogger
- http-client
- http-conduit
- http-types
- network
- record-hasfield
- rio
- scotty
- serialise
- stm
- time
- typed-process
- wai-cors
- yaml

ghc-options:
- -F -pgmF=record-dot-preprocessor
- -fwarn-tabs
- -fwarn-unused-imports

library:
  source-dirs: src

executables:
  turnstile:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turnstile

tests:
  turnstile-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turnstile
    - hspec
